#define MAX_VERTICES_SIZE 65535
#define MAX_INDICES_SIZE 65535

struct Index {
  uint Vertex;
  uint Normal;
  uint Texture;
};

struct MeshBufferData{
  uint VerticesSize; //1N
  uint NormalsSize; //1N
  uint TexturesSize; //1N
  uint IndiciesSize; //1N
  vec4 Center; //4N
  mat4 Transformation; //16N 
  vec4 Vertices[MAX_VERTICES_SIZE];
  vec4 Normals[MAX_VERTICES_SIZE];
  vec2 Textures[MAX_VERTICES_SIZE];
  Index Indices[MAX_INDICES_SIZE];
  float Bounds; //1N
};