
#define MAX_STEPS 100
#define MAX_DIST 100.
#define SURF_DIST .01

float GetMinDistance(vec3 point);

float RayMarch(vec3 rayOrigin, vec3 rayDirection) {
  float distanceFromOrigin = 0.;
  for (int i = 0; i < MAX_STEPS; i++) {
    vec3 rayLocation = rayOrigin + (distanceFromOrigin * rayDirection);
    float dist = GetMinDistance(rayLocation);
    distanceFromOrigin += dist;
    if (distanceFromOrigin < SURF_DIST || distanceFromOrigin > MAX_DIST)
      break;
  }
  return distanceFromOrigin;
}