#ifndef _CORE_KEY_CODE
#define _CORE_KEY_CODE

#include <SDL2/SDL.h>

namespace Tortuga
{
namespace Core
{
namespace Input
{
enum KeyAction
{
  Released = 0,
  Pressed = 1,
  HeldDown = 2
};
enum KeyCode
{
  Unknown = -1,
  MOUSE_BUTTON_1 = 0,
  MOUSE_BUTTON_2 = 1,
  MOUSE_BUTTON_3 = 2,
  MOUSE_BUTTON_4 = 3,
  MOUSE_BUTTON_5 = 4,
  MOUSE_BUTTON_6 = 5,
  MOUSE_BUTTON_7 = 6,
  MOUSE_BUTTON_8 = 7,
  MOUSE_BUTTON_9 = 8,
  MOUSE_BUTTON_LEFT = MOUSE_BUTTON_1,
  MOUSE_BUTTON_MIDDLE = MOUSE_BUTTON_2,
  MOUSE_BUTTON_RIGHT = MOUSE_BUTTON_3,
  Space = SDLK_SPACE,
  Apostrophe = SDLK_QUOTE,
  Comma = SDLK_COMMA,
  Minus = SDLK_MINUS,
  Period = SDLK_PERIOD,
  Slash = SDLK_SLASH,
  Zero = SDLK_0,
  One = SDLK_1,
  Two = SDLK_2,
  Three = SDLK_3,
  Four = SDLK_4,
  Five = SDLK_5,
  Six = SDLK_6,
  Seven = SDLK_7,
  Eight = SDLK_8,
  Nine = SDLK_9,
  Semicolon = SDLK_SEMICOLON,
  Equal = SDLK_EQUALS,
  A = SDLK_a,
  B = SDLK_b,
  C = SDLK_c,
  D = SDLK_d,
  E = SDLK_e,
  F = SDLK_f,
  G = SDLK_g,
  H = SDLK_h,
  I = SDLK_i,
  J = SDLK_j,
  K = SDLK_k,
  L = SDLK_l,
  M = SDLK_m,
  N = SDLK_n,
  O = SDLK_o,
  P = SDLK_p,
  Q = SDLK_q,
  R = SDLK_r,
  S = SDLK_s,
  T = SDLK_t,
  U = SDLK_u,
  V = SDLK_v,
  W = SDLK_w,
  X = SDLK_x,
  Y = SDLK_y,
  Z = SDLK_z,
  LeftBracket = SDLK_LEFTBRACKET,
  BackSlash = SDLK_BACKSLASH,
  RightBracket = SDLK_RIGHTBRACKET,
  GraveAccent = SDLK_BACKQUOTE,
  Escape = SDLK_ESCAPE,
  Enter = SDLK_RETURN,
  Tab = SDLK_TAB,
  Backspace = SDLK_BACKSPACE,
  Insert = SDLK_INSERT,
  Delete = SDLK_DELETE,
  Right = SDLK_RIGHT,
  Left = SDLK_LEFT,
  Down = SDLK_DOWN,
  Up = SDLK_UP,
  PageUp = SDLK_PAGEUP,
  PageDown = SDLK_PAGEDOWN,
  Home = SDLK_HOME,
  End = SDLK_HOME,
  CapsLock = SDLK_CAPSLOCK,
  ScrollLock = SDLK_SCROLLLOCK,
  NumLock = SDLK_NUMLOCKCLEAR,
  PrintScreen = SDLK_PRINTSCREEN,
  Pause = SDLK_PAUSE,
  F1 = SDLK_F1,
  F2 = SDLK_F2,
  F3 = SDLK_F3,
  F4 = SDLK_F4,
  F5 = SDLK_F5,
  F6 = SDLK_F6,
  F7 = SDLK_F7,
  F8 = SDLK_F8,
  F9 = SDLK_F9,
  F10 = SDLK_F10,
  F11 = SDLK_F11,
  F12 = SDLK_F12,
  F13 = SDLK_F13,
  F14 = SDLK_F14,
  F15 = SDLK_F15,
  F16 = SDLK_F16,
  F17 = SDLK_F17,
  F18 = SDLK_F18,
  F19 = SDLK_F19,
  F20 = SDLK_F20,
  F21 = SDLK_F21,
  F22 = SDLK_F22,
  F23 = SDLK_F23,
  F24 = SDLK_F24,
  KeyPad0 = SDLK_KP_0,
  KeyPad1 = SDLK_KP_1,
  KeyPad2 = SDLK_KP_2,
  KeyPad3 = SDLK_KP_3,
  KeyPad4 = SDLK_KP_4,
  KeyPad5 = SDLK_KP_5,
  KeyPad6 = SDLK_KP_6,
  KeyPad7 = SDLK_KP_7,
  KeyPad8 = SDLK_KP_8,
  KeyPad9 = SDLK_KP_9,
  KeyPadDecimal = SDLK_KP_DECIMAL,
  KeyPadDivide = SDLK_KP_DIVIDE,
  KeyPadMultiply = SDLK_KP_MULTIPLY,
  KeyPadSubtract = SDLK_KP_MEMSUBTRACT,
  KeyPadAdd = SDLK_KP_MEMADD,
  KeyPadEnter = SDLK_KP_ENTER,
  KeyPadEqual = SDLK_KP_EQUALS,
  LeftShift = SDLK_LSHIFT,
  LeftControl = SDLK_LCTRL,
  LeftAlt = SDLK_LALT,
  RightShift = SDLK_RSHIFT,
  RightControl = SDLK_RCTRL,
  RightAlt = SDLK_RALT
};
} // namespace Input
} // namespace Core
} // namespace Tortuga

#endif