#version 450

layout(set = 0, binding = 0) readonly buffer InputBuffer {
  uint ResolutionX;
  uint ResolutionY;
}
inputBuffer;

struct Pixel {
  float r;
  float g;
  float b;
  float a;
};
layout(set = 0, binding = 1) buffer OutputBuffer { Pixel[] Pixels; }
outputBuffer;

void main() {
  for (uint i = 0; i < 480000; i++) {
    outputBuffer.Pixels[i].r = 255;
    outputBuffer.Pixels[i].g = 255;
    outputBuffer.Pixels[i].b = 255;
    outputBuffer.Pixels[i].a = 1;
  }
}